# kitty — arch_setup
# TODO : fusionner avec la conf récupérée d'Ubuntu (Migration Ubuntu → Arch)
include ~/.config/themes/current/colors-kitty.conf
font_family JetBrainsMono Nerd Font
font_size 11.0
enable_audio_bell no
confirm_os_window_close 0
allow_remote_control yes   # requis pour theme-set (rechargement couleurs à chaud)
